### ISSUE TITLE
barebones package broken

### ISSUE THREAD

**Issue by jlbosse** [rigetti/quilc#321]
Since Version 2.8 the barebones package is broken. The installer works fine, but if I run `quilc -R` I get the following output:

```
Unhandled CFFI:LOAD-FOREIGN-LIBRARY-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                       {10006B85B3}>:
  Unable to load any of the alternatives:
   (#P"/src/quilc/src/contrib/tweedledum/libtweedledum.so" "libtweedledum.so"
    "tweedledum.so")

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006B85B3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<CFFI:LOAD-FOREIGN-LIBRARY-ERROR "Unable to load any of the alternatives:~%   ~S" {1004DEB793}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<CFFI:LOAD-FOREIGN-LIBRARY-ERROR "Unable to load any of the alternatives:~%   ~S" {1004DEB793}>)
2: (INVOKE-DEBUGGER #<CFFI:LOAD-FOREIGN-LIBRARY-ERROR "Unable to load any of the alternatives:~%   ~S" {1004DEB793}>)
3: (ERROR CFFI:LOAD-FOREIGN-LIBRARY-ERROR :FORMAT-CONTROL "Unable to load any of the alternatives:~%   ~S" :FORMAT-ARGUMENTS ((#P"/src/quilc/src/contrib/tweedledum/libtweedledum.so" "libtweedledum.so" "tweedledum.so")))
4: (CFFI::FL-ERROR "Unable to load any of the alternatives:~%   ~S" (#P"/src/quilc/src/contrib/tweedledum/libtweedledum.so" "libtweedledum.so" "tweedledum.so"))
5: (CFFI::TRY-FOREIGN-LIBRARY-ALTERNATIVES CL-QUIL.TWEEDLEDUM::LIBTWEEDLEDUM (#P"/src/quilc/src/contrib/tweedledum/libtweedledum.so" "libtweedledum.so" "tweedledum.so") (#P"/usr/local/lib/rigetti/"))
6: ((FLET CFFI::%DO-LOAD :IN CFFI::%DO-LOAD-FOREIGN-LIBRARY) #<CFFI:FOREIGN-LIBRARY LIBTWEEDLEDUM> CL-QUIL.TWEEDLEDUM::LIBTWEEDLEDUM (:OR #P"/src/quilc/src/contrib/tweedledum/libtweedledum.so" "libtweedledum.so" "tweedledum.so"))
7: (CFFI:LOAD-FOREIGN-LIBRARY CL-QUIL.TWEEDLEDUM::LIBTWEEDLEDUM :SEARCH-PATH NIL)
8: (CL-QUIL.TWEEDLEDUM:LOAD-TWEEDLEDUM)
9: (QUILC::ENTRY-POINT ("quilc" "-R"))
10: ((LAMBDA NIL :IN MAKE-TOPLEVEL-FUNCTION))
11: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
13: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
```

this might be related to https://github.com/rigetti/quilc/issues/254

**Comment by jmbr** [comment]
Thank you, @jlbosse. We have a potential fix on the pipeline.

**Comment by notmgsk** [comment]
This ought to have been fixed in the latest release (SDK version 2.9): https://downloads.rigetti.com/qcs-sdk/forest-sdk-linux-barebones.tar.bz2

**Comment by jlbosse** [comment]
Just tested with the version from the link again. The error persists. I also tried installing it with sudoers rights, to no avail. Or do I have to clone this repo compile quilc on my own machine, to get it working?

**Comment by jmbr** [comment]
Thank you for the heads up. The docker container should work without you cloning and compiling quilc on your own machine. While we look into this you can run quilc using:

``` bash
export LD_LIBRARY-PATH=/path/to/forest-sdk_2.9.0-linux-barebones
quilc -R
```

**Comment by jlbosse** [comment]
Great, thanks for the tip! I didn't realize it was that easy to get a work around.

For others reading this: The first command should be 
`export LD_LIBRARY_PATH=/...`
(underscore instead of hyphen)

**Comment by jmbr** [comment]
Thanks, @jlbosse  I just updated my comment above :-)
